config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games, except: %i[destroy] do
    patch :move_piece, on: :member
    patch :promotion, on: :member
    post :check_positions, on: :member
    get :join, on: :member
  end
  root "home#index"
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :users, through: :matches
  has_many :matches

  validates :time, presence: true
  validates :theme, presence: true
  validates :mode, presence: true

  attribute :time, :integer, default: 0
  attribute :players, :integer, default: 0
  attribute :theme, :integer, default: 0
  attribute :mode, :integer, default: 0
  attribute :turn, :integer, default: 0
  attribute :status, :integer, default: 0
  attribute :moves, :json, default: []
  attribute :promotion, :json, default: []

  enum time: { ten_minutes: 0, five_minutes: 1, one_minute: 2 }
  enum theme: { default: 0, harry_potter: 1, lotr: 2 }
  enum mode: { one_vs_one: 0, two_vs_two: 1, free_for_all: 2 }
  enum status: { open: 0, ongoing: 1, finished: 2 }

  before_create :set_board

  after_update_commit { broadcast_update }

  def set_board
    self.state = case mode
                 when 'one_vs_one'
                   [
                     ['rock_2', 'knight_2', 'bishop_2', 'queen_2', 'king_2', 'bishop_2', 'knight_2', 'rock_2'],
                     ['pawn_2', 'pawn_2', 'pawn_2', 'pawn_2', 'pawn_2', 'pawn_2', 'pawn_2', 'pawn_2'],
                     ['', '', '', '', '', '', '', ''],
                     ['', '', '', '', '', '', '', ''],
                     ['', '', '', '', '', '', '', ''],
                     ['', '', '', '', '', '', '', ''],
                     ['pawn_1', 'pawn_1', 'pawn_1', 'pawn_1', 'pawn_1', 'pawn_1', 'pawn_1', 'pawn_1'],
                     ['rock_1', 'knight_1', 'bishop_1', 'queen_1', 'king_1', 'bishop_1', 'knight_1', 'rock_1']
                   ]
                 when 'two_vs_two'
                   [
                     ['x', 'x', 'x', 'rock_5', 'knight_5', 'bishop_5', 'queen_5', 'king_5', 'bishop_5', 'knight_5', 'rock_5', 'x', 'x', 'x'],
                     ['x', 'x', 'x', 'pawn_5', 'pawn_5', 'pawn_5', 'pawn_5', 'pawn_5', 'pawn_5', 'pawn_5', 'pawn_5', 'x', 'x', 'x'],
                     ['x', 'x', 'x', '', '', '', '', '', '', '', '', 'x', 'x', 'x'],
                     ['rock_4', 'pawn_4', '', '', '', '', '', '', '', '', '', '', 'pawn_6', 'rock_6'],
                     ['knight_4', 'pawn_4', '', '', '', '', '', '', '', '', '', '', 'pawn_6', 'knight_6'],
                     ['bishop_4', 'pawn_4', '', '', '', '', '', '', '', '', '', '', 'pawn_6', 'bishop_6'],
                     ['king_4', 'pawn_4', '', '', '', '', '', '', '', '', '', '', 'pawn_6', 'queen_6'],
                     ['queen_4', 'pawn_4', '', '', '', '', '', '', '', '', '', '', 'pawn_6', 'king_6'],
                     ['bishop_4', 'pawn_4', '', '', '', '', '', '', '', '', '', '', 'pawn_6', 'bishop_6'],
                     ['knight_4', 'pawn_4', '', '', '', '', '', '', '', '', '', '', 'pawn_6', 'knight_6'],
                     ['rock_4', 'pawn_4', '', '', '', '', '', '', '', '', '', '', 'pawn_6', 'rock_6'],
                     ['x', 'x', 'x', '', '', '', '', '', '', '', '', 'x', 'x', 'x'],
                     ['x', 'x', 'x', 'pawn_3', 'pawn_3', 'pawn_3', 'pawn_3', 'pawn_3', 'pawn_3', 'pawn_3', 'pawn_3', 'x', 'x', 'x'],
                     ['x', 'x', 'x', 'rock_3', 'knight_3', 'bishop_3', 'queen_3', 'king_3', 'bishop_3', 'knight_3', 'rock_3', 'x', 'x', 'x']
                   ]
                 when 'free_for_all'
                   [
                     ['rock_2', 'knight_2', 'bishop_2', 'queen_2', 'king_2', 'bishop_2', 'knight_2', 'rock_2'],
                     ['pawn_2', 'pawn_2', 'pawn_2', 'pawn_2', 'pawn_2', 'pawn_2', 'pawn_2', 'pawn_2'],
                     ['', '', '', '', '', '', '', ''],
                     ['', '', '', '', '', '', '', ''],
                     ['', '', '', '', '', '', '', ''],
                     ['', '', '', '', '', '', '', ''],
                     ['', '', '', '', '', '', '', ''],
                     ['', '', '', '', '', '', '', ''],
                     ['', '', '', '', '', '', '', ''],
                     ['pawn_1', 'pawn_1', 'pawn_1', 'pawn_1', 'pawn_1', 'pawn_1', 'pawn_1', 'pawn_1'],
                     ['rock_1', 'knight_1', 'bishop_1', 'queen_1', 'king_1', 'bishop_1', 'knight_1', 'rock_1']
                   ] end
  end

  def check_available_positions(piece, startx, starty)
    valid_positions = []
    state.each_with_index do |row, row_index|
      row.each_with_index do |_col, col_index|
        next unless valid_target?(startx, starty, row_index, col_index)

        case piece
        when 'pawn_1'
          valid_positions << [row_index, col_index] if pawn_one(startx, starty, row_index, col_index)
        when 'pawn_2'
          valid_positions << [row_index, col_index] if pawn_two(startx, starty, row_index, col_index)
        when 'knight_1', 'knight_2'
          valid_positions << [row_index, col_index] if knight(startx, starty, row_index, col_index)
        when 'bishop_1', 'bishop_2'
          valid_positions << [row_index, col_index] if valid_diagonal_move?(startx, starty, row_index, col_index) && !obstacles_on_path?(startx, starty, row_index, col_index)
        when 'rock_1', 'rock_2'
          valid_positions << [row_index, col_index] if valid_straight_move?(startx, starty, row_index, col_index) && !obstacles_on_path?(startx, starty, row_index, col_index)
        when 'queen_1', 'queen_2'
          valid_positions << [row_index, col_index] if (valid_straight_move?(startx, starty, row_index,
                                                                             col_index) || valid_diagonal_move?(startx, starty, row_index,
                                                                                                                col_index)) && !obstacles_on_path?(startx, starty, row_index, col_index)
        when 'king_1', 'king_2'

          valid_positions << [row_index, col_index] if (starty - col_index).abs <= 1 && (startx - row_index).abs <= 1 && !obstacles_on_path?(startx, starty, row_index, col_index)
        end
      end
    end
    valid_positions
  end

  def check_mate
    return false if check_check[0] == false && check_check[1] == false

    if turn.even? && check_check[0]
      white_valid_positions = []
      state.each_with_index do |row, row_index|
        row.each_with_index do |col, col_index|
          next if col.empty? || col.split('_')[1].to_i == 2

          white_valid_positions = check_available_positions(col, col_index, row_index) if col.split('_')[1].to_i == 1

          white_valid_positions.each do |position|
            moved_piece = state[row_index][col_index]
            target_position = state[position[1]][position[0]]

            state[position[1]][position[0]] = moved_piece
            state[row_index][col_index] = ''

            unless check_check[0]
              state[row_index][col_index] = moved_piece
              state[position[1]][position[0]] = target_position
              return false
            end

            state[row_index][col_index] = moved_piece
            state[position[1]][position[0]] = target_position
          end
        end
      end
    end

    if turn.odd? && check_check[1]
      black_valid_positions = []
      state.each_with_index do |row, row_index|
        row.each_with_index do |col, col_index|
          next if col.empty? || col.split('_')[1].to_i == 1

          black_valid_positions = check_available_positions(col, col_index, row_index) if col.split('_')[1].to_i == 2

          black_valid_positions.each do |position|
            moved_piece = state[row_index][col_index]
            target_position = state[position[1]][position[0]]

            state[position[1]][position[0]] = moved_piece
            state[row_index][col_index] = ''

            unless check_check[1]
              state[row_index][col_index] = moved_piece
              state[position[1]][position[0]] = target_position
              return false

            end

            state[row_index][col_index] = moved_piece
            state[position[1]][position[0]] = target_position
          end
        end
      end

    end
    true
  end

  def check_check
    white_valid_positions = []
    black_valid_positions = []
    white_king = []
    black_king = []
    state.each_with_index do |row, row_index|
      row.each_with_index do |col, col_index|
        next if col.empty?

        white_king = [col_index, row_index] if col == 'king_1'
        black_king = [col_index, row_index] if col == 'king_2'

        white_valid_positions << check_available_positions(col, col_index, row_index) if col.split('_')[1].to_i == 1
        black_valid_positions << check_available_positions(col, col_index, row_index) if col.split('_')[1].to_i == 2
      end
    end
    # [is white king in check, is black king in check]
    [black_valid_positions.flatten(1).include?(white_king), white_valid_positions.flatten(1).include?(black_king)]
  end

  def valid_target?(startx, starty, finishx, finishy)
    # Checks if it is empty or if it is same team piece
    (state[finishy][finishx].blank? || state[finishy][finishx].split('_')[1] != state[starty][startx].split('_')[1]) && state[starty][startx] != '' && state[finishx][finishy] != 'x'
  end

  def case_move(piece, startx, starty, finishx, finishy)
    return unless valid_target?(startx, starty, finishx, finishy)

    case piece
    when 'pawn_1'
      move_piece(startx, starty, finishx, finishy) if pawn_one(startx, starty, finishx, finishy)
    when 'pawn_2'
      move_piece(startx, starty, finishx, finishy) if pawn_two(startx, starty, finishx, finishy)
    when 'knight_1', 'knight_2'
      move_piece(startx, starty, finishx, finishy) if knight(startx, starty, finishx, finishy)
    when 'bishop_1', 'bishop_2'
      move_piece(startx, starty, finishx, finishy) if valid_diagonal_move?(startx, starty, finishx, finishy) && !obstacles_on_path?(startx, starty, finishx, finishy)
    when 'rock_1', 'rock_2'
      move_piece(startx, starty, finishx, finishy) if valid_straight_move?(startx, starty, finishx, finishy) && !obstacles_on_path?(startx, starty, finishx, finishy)

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update move_piece join check_positions promotion]
  before_action :authenticate_user!

  def index
    @mini_games = Game.all.order(id: :asc)
  end

  def show; end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(params_required)
    @match = Match.new(game: @game, user: current_user, color: ['white', 'black'].sample)
    if @game.save && @match.save
      @game.increment!(:players)
      redirect_to game_path(@game), notice: 'Game was successfully created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update; end

  def move_piece
    color = current_user.matches.where(game: @game)[0].color
    if @game.status == "ongoing"
      if @game.turn.even? && color == 'white'
        @game.move(params[:piece], params[:currentx].to_i, params[:currenty].to_i, params[:targetx].to_i, params[:targety].to_i)
      end
      if @game.turn.odd? && color == 'black'
        @game.move(params[:piece], params[:currentx].to_i, params[:currenty].to_i, params[:targetx].to_i, params[:targety].to_i)
      end
      redirect_to game_path(@game)
    end
  end

  def check_positions
    available_positions = @game.check_available_positions(params[:piece], params[:currentx].to_i, params[:currenty].to_i)
    @game.check_check
    render json: available_positions
  end

  def promotion
    @game.set_promotion(params[:currenty], params[:currentx], params[:piece])
    redirect_to game_path(@game)
  end

  def join
    if !@game.matches.any? { |obj| obj.user_id == current_user.id }
      @game.increment!(:players)
      colors = @game.matches.map { |obj| obj.color }
      all_colors = Match.colors.keys
      available_colors = all_colors - colors
      Match.create!(game: @game, user: current_user, color: available_colors.sample)
      if @game.mode == "one_vs_one" && @game.players == 2
        @game.status = "ongoing"
        @game.save
      end
    end

    redirect_to game_path(@game)
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def params_required
    params.require(:game).permit(:state, :players, :turn, :moves, :time, :status, :theme, :mode)
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def get_moves(game)
    game.moves.map do |subarray|
      letters = ('a'..'h').to_a
      numbers = (1..8).to_a.reverse
      [[letters[subarray[0]], numbers[subarray[1]], letters[subarray[2]], numbers[subarray[3]]].join, subarray[4], subarray[5]]
    end
  end
end

app/views/games/_game.html.erb
<% moves = get_moves(game) %>
<% matches = game.matches %>

<% if matches.find { |obj| obj[:color] == "black" } %>
  <% black_player_match = matches.find { |obj| obj[:color] == "black" } %>
  <% black_player = User.find(black_player_match.user_id) %>
<% end %>

<% if matches.find { |obj| obj[:color] == "white" } %>
  <% white_player_match = matches.find { |obj| obj[:color] == "white" } %>
  <% white_player = User.find(white_player_match.user_id) %>
<% end %>

<div class="<%= current_user == white_player ? "game" : "game inverted" %>">
  <div class="<%= current_user == white_player ? "player-info" : "player-info inverted" %>">
    <div class="player">
      <div class="player-image">
        Image
      </div>
      <div class="name-and-pieces">
        <p><%= black_player ? black_player.name : "Waiting for opponent" %></p>
        <div class="killed-pieces">
          <% moves.each do |move| %>
            <% if move[2] != '' && move[2].split('_')[1] != '2' %>
              <%= image_tag("pieces/" + move[2] + ".png", class: "killed-piece") %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="<%= game.turn.odd? ? "timer activated" : "timer" %>">
      <div id="countdown1">
      </div>
    </div>
  </div>

  <%unless game.moves.empty?%>
    <% finish_x = game.moves[-1][2] %>
    <% finish_y = game.moves[-1][3] %>
  <% end %>

  <div class="board" data-controller="drag">
    <% game.state.each_with_index do |row, row_index| %>
      <div class='row'>
        <% row.each_with_index do |cell, cell_index| %>
        <div class="cell <%= cell %> <%= finish_x == cell_index && finish_y == row_index ? 'last-move' : ''%>" id=<%= "#{cell}-#{game.id}-#{cell_index}-#{row_index}" %> data-action="dragstart->drag#dragStart dragover->drag#dragOver dragenter->drag#dragEnter drop->drag#dragDrop dragend->drag#dragEnd dragleave->drag#dragLeave">
          <% if !cell.empty? && cell != 'x' %>
            <%= image_tag("pieces/#{cell}.png", class: current_user == white_player ? "test" : "test inverted", id: "#{cell}-#{game.id}-#{cell_index}-#{row_index}", draggable: "true") %>
          <% else %>
            <%= cell %>
          <% end %>
        </div>
        <% end %>
      </div>
    <% end %>

    <% if game.status == 'finished' %>
      <div class="finished">
        <button class="close-button button2">X</button>
        <% if game.status == "finished" && game.turn.even? %>
          <h2>Black Won!</h2>
        <% else %>
          <h2>White Won!</h2>
        <% end %>
        <p>Check Mate!</p>
        <p>Rating 614 +8</p>
        <p>Rating 614 -8</p>
        <%= link_to "New game", new_game_path, class: "button1" %>
      </div>
    <% end %>

    <% if !game.promotion.empty? %>
      <div class="finished">
        Promotion
        <div>
        <% if game.turn.odd? %>
          <button class="promotion-selected rock_1" id="<%= "rock_1-#{game.id}-#{game.promotion[0]}-#{game.promotion[1]}-#{game.promotion[2]}"%>"></button>
          <button class="promotion-selected knight_1" id="<%= "knight_1-#{game.id}-#{game.promotion[0]}-#{game.promotion[1]}-#{game.promotion[2]}"%>"></button>
          <button class="promotion-selected bishop_1" id="<%= "bishop_1-#{game.id}-#{game.promotion[0]}-#{game.promotion[1]}-#{game.promotion[2]}"%>"></button>
          <button class="promotion-selected queen_1" id="<%= "queen_1-#{game.id}-#{game.promotion[0]}-#{game.promotion[1]}-#{game.promotion[2]}"%>"></button>
        <% else %>
          <button class="promotion-selected rock_2" id="<%= "rock_2-#{game.id}-#{game.promotion[0]}-#{game.promotion[1]}-#{game.promotion[2]}"%>"></button>
          <button class="promotion-selected knight_2" id="<%= "knight_2-#{game.id}-#{game.promotion[0]}-#{game.promotion[1]}-#{game.promotion[2]}"%>"></button>
          <button class="promotion-selected bishop_2" id="<%= "bishop_2-#{game.id}-#{game.promotion[0]}-#{game.promotion[1]}-#{game.promotion[2]}"%>"></button>
          <button class="promotion-selected queen_2" id="<%= "queen_2-#{game.id}-#{game.promotion[0]}-#{game.promotion[1]}-#{game.promotion[2]}"%>"></button>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="<%= current_user == white_player ? "player-info" : "player-info inverted" %>">
    <div class="player">
      <div class="player-image">
        Image
      </div>
      <div class="name-and-pieces">
        <p><%= white_player ? white_player.name : "Waiting for opponent" %></p>
        <div class="killed-pieces">
          <% moves.each do |move| %>
            <% if move[2] != '' && move[2].split('_')[1] != '1' %>
              <%= image_tag("pieces/" + move[2] + ".png", class: "killed-piece") %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="<%= game.turn.even? ? "timer activated" : "timer" %>">
      <div id="countdown2">
      </div>
    </div>

  </div>
</div>

<div class="information">
  <div class="information-div">
    <h1>Game #<%= game.id %></h1>
    <h2><%= game.status %></h2>
    <p>Players: <%= game.players %></p>
    <p>Turn: <%= game.turn % 2 == 0 ? "White" : "Black" %></p>
  </div>

  <div class="information-div">
    <p>Moves:</p>
      <div id="moves">
      <% if moves %>
          <table>
            <thead>
              <tr>
                <th>Movement</th>
                <th>Piece</th>
                <th>From</th>
                <th>To</th>
                <th>Target</th>
              </tr>
            </thead>
            <% moves.each_with_index do |move, index| %>
            <tbody>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= image_tag("pieces/" + move[1] + ".png", class: "movement-image") %></td>
                <td><%= move[0][0] + move[0][1] %></td>
                <td><%= move[0][2] + move[0][3] %></td>
                <% if !move[2].empty? %>
                  <td><%= image_tag("pieces/" + move[2] + ".png", class: "movement-image") %></td>
                <% else %>
                  <td>-</td>
                <% end %>
              </tr>
            </tbody>
            <% end %>
          </table>
      <% end %>
    </div>
  </div>

  <div class="information-div"  >
    <%= link_to "Surrender", games_path, class: "button2" %>
  </div>
</div>

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<p>Find me in app/views/games/edit.html.erb</p>

app/views/games/index.html.erb
<div id="games-container">
  <h1>Games</h1>
  <div id="games">
    <% @mini_games.each do |game| %>
      <div class="mini-game">    
        <div class="mini-board">
          <% game.state.each do |row| %>
          <div class='mini-row'>
            <% row.each do |cell| %>
              <div class="mini-cell <%= cell %>">
                <% if !cell.empty? && cell != 'x' %>
                  <%= image_tag("pieces/#{cell}.png", class: "mini-image") %>
                <% else %>
                  <%= cell %>
                <% end %>
              </div>
            <% end %>
          </div>
          <% end %>
        </div>

        <div class="mini-game-info">
          <p><%= link_to game.mode, game_path(game), class: "button1" %></p>
          <% if game.matches.any? { |obj| obj.user_id == current_user.id }%>
            <p><%= link_to 'Resume', game_path(game), class: "join-button" %></p>
          <% elsif game.mode == "one_vs_one" && game.players < 2 %>
            <p><%= link_to 'Join', join_game_path(game), class: "join-button" %></p>
          <% end %>
          <p>Status: <%= game.status %></p>
          <p>Mode: <%= game.mode %></p>
          <p>Theme: <%= game.theme %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<h1>New Game</h1>
<%= form_with model: @game do |form| %>
  <%#= form.select :time %>
  <%#= form.select :theme %>
  <%#= form.select :mode %>

  <%= form.select :theme, Game.themes.keys.map { |theme| [theme.humanize, theme] } %>
  <%= form.select :mode, Game.modes.keys.map { |mode| [mode.humanize, mode] } %>
  <%= form.select :time, Game.times.keys.map { |time| [time.humanize, time] } %>

  <%= form.submit "Start New Game", class: "button1" %>
<% end %>

app/views/games/show.html.erb
<%= turbo_stream_from @game %>

<div id="<%= dom_id(@game) %>" class="game-container">
  <%= render @game %>
</div>

app/views/games/update.html.erb
<h1>Games#update</h1>
<p>Find me in app/views/games/update.html.erb</p>